### ISSUE TITLE
Stuff that needs to be fixed

### ISSUE THREAD

**Issue by GOAF-Pilot** [GOAF-Pilot/CountDown#1]
/ns are not needed
Get rid of months, and have it say weeks, etc.
Get rid of the word and, it is implied.
Add background
Better, bolder font. Maybe text shadow
Text stand out against background

**Comment by izzyboymeme** [comment]
Got rid of /ns, months and word and, also variablize Y-axis positioning. (windowHeight)

**Comment by GOAF-Pilot** [comment]
Added some text shadowing that could be refined, added background, could be refined. Changed font size
